/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  account_info: () => import("@/views/account/info/index.vue"),
  account_notice: () => import("@/views/account/notice/index.vue"),
  dev_apidoc: () => import("@/views/dev/apidoc/index.vue"),
  dev_gen: () => import("@/views/dev/gen/index.vue"),
  home: () => import("@/views/home/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  ops_filter: () => import("@/views/ops/filter/index.vue"),
  "ops_job-log": () => import("@/views/ops/job-log/index.vue"),
  ops_job: () => import("@/views/ops/job/index.vue"),
  ops_online: () => import("@/views/ops/online/index.vue"),
  "ops_operate-log": () => import("@/views/ops/operate-log/index.vue"),
  org_dept: () => import("@/views/org/dept/index.vue"),
  org_post: () => import("@/views/org/post/index.vue"),
  setting_config: () => import("@/views/setting/config/index.vue"),
  setting_dict: () => import("@/views/setting/dict/index.vue"),
  setting_file: () => import("@/views/setting/file/index.vue"),
  "setting_notice-console": () => import("@/views/setting/notice-console/index.vue"),
  setting_notice: () => import("@/views/setting/notice/index.vue"),
};
