/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'account',
    path: '/account',
    component: 'layout.base',
    meta: {
      title: 'account',
      i18nKey: 'route.account',
      hideInMenu: true
    },
    children: [
      {
        name: 'account_info',
        path: '/account/info',
        component: 'view.account_info',
        meta: {
          title: 'account_info',
          i18nKey: 'route.account_info',
          icon: 'ic:round-person'
        }
      },
      {
        name: 'account_notice',
        path: '/account/notice',
        component: 'view.account_notice',
        meta: {
          title: 'account_notice',
          i18nKey: 'route.account_notice',
          icon: 'mdi:bell-outline'
        }
      }
    ]
  },
  {
    name: 'dev',
    path: '/dev',
    component: 'layout.base',
    meta: {
      title: 'dev',
      i18nKey: 'route.dev',
      icon: 'mdi:tools',
      order: 90
    },
    children: [
      {
        name: 'dev_apidoc',
        path: '/dev/apidoc',
        component: 'view.dev_apidoc',
        meta: {
          title: 'dev_apidoc',
          i18nKey: 'route.dev_apidoc',
          icon: 'mdi:api'
        }
      },
      {
        name: 'dev_gen',
        path: '/dev/gen',
        component: 'view.dev_gen',
        meta: {
          title: 'dev_gen',
          i18nKey: 'route.dev_gen',
          icon: 'mdi:code-tags'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 2
    },
    children: [
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role'
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts'
        }
      }
    ]
  },
  {
    name: 'ops',
    path: '/ops',
    component: 'layout.base',
    meta: {
      title: 'ops',
      i18nKey: 'route.ops',
      icon: 'mdi:shield-lock-outline',
      order: 4
    },
    children: [
      {
        name: 'ops_filter',
        path: '/ops/filter',
        component: 'view.ops_filter',
        meta: {
          title: 'ops_filter',
          i18nKey: 'route.ops_filter',
          icon: 'mdi:filter-outline'
        }
      },
      {
        name: 'ops_job',
        path: '/ops/job',
        component: 'view.ops_job',
        meta: {
          title: 'ops_job',
          i18nKey: 'route.ops_job',
          icon: 'mdi:clock-outline'
        }
      },
      {
        name: 'ops_job-log',
        path: '/ops/job-log',
        component: 'view.ops_job-log',
        meta: {
          title: 'ops_job-log',
          i18nKey: 'route.ops_job-log',
          icon: 'mdi:text-box-outline',
          hideInMenu: true,
          activeMenu: 'ops_job'
        }
      },
      {
        name: 'ops_online',
        path: '/ops/online',
        component: 'view.ops_online',
        meta: {
          title: 'ops_online',
          i18nKey: 'route.ops_online',
          icon: 'mdi:account-check-outline'
        }
      },
      {
        name: 'ops_operate-log',
        path: '/ops/operate-log',
        component: 'view.ops_operate-log',
        meta: {
          title: 'ops_operate-log',
          i18nKey: 'route.ops_operate-log',
          icon: 'mdi:history'
        }
      }
    ]
  },
  {
    name: 'org',
    path: '/org',
    component: 'layout.base',
    meta: {
      title: 'org',
      i18nKey: 'route.org',
      icon: 'mdi:account-group-outline',
      order: 2
    },
    children: [
      {
        name: 'org_dept',
        path: '/org/dept',
        component: 'view.org_dept',
        meta: {
          title: 'org_dept',
          i18nKey: 'route.org_dept',
          icon: 'mdi:sitemap-outline'
        }
      },
      {
        name: 'org_post',
        path: '/org/post',
        component: 'view.org_post',
        meta: {
          title: 'org_post',
          i18nKey: 'route.org_post',
          icon: 'mdi:briefcase-outline'
        }
      }
    ]
  },
  {
    name: 'setting',
    path: '/setting',
    component: 'layout.base',
    meta: {
      title: 'setting',
      i18nKey: 'route.setting',
      icon: 'mdi:cog-outline',
      order: 3
    },
    children: [
      {
        name: 'setting_config',
        path: '/setting/config',
        component: 'view.setting_config',
        meta: {
          title: 'setting_config',
          i18nKey: 'route.setting_config',
          icon: 'mdi:tune-variant'
        }
      },
      {
        name: 'setting_dict',
        path: '/setting/dict',
        component: 'view.setting_dict',
        meta: {
          title: 'setting_dict',
          i18nKey: 'route.setting_dict',
          icon: 'mdi:book-alphabet'
        }
      },
      {
        name: 'setting_file',
        path: '/setting/file',
        component: 'view.setting_file',
        meta: {
          title: 'setting_file',
          i18nKey: 'route.setting_file',
          icon: 'mdi:file-multiple-outline'
        }
      },
      {
        name: 'setting_notice',
        path: '/setting/notice',
        component: 'view.setting_notice',
        meta: {
          title: 'setting_notice',
          i18nKey: 'route.setting_notice',
          icon: 'mdi:bullhorn-outline'
        }
      },
      {
        name: 'setting_notice-console',
        path: '/setting/notice-console',
        component: 'view.setting_notice-console',
        meta: {
          title: 'setting_notice-console',
          i18nKey: 'route.setting_notice-console',
          icon: 'mdi:chart-box-outline',
          hideInMenu: true,
          activeMenu: 'setting_notice'
        }
      }
    ]
  }
];
